### ISSUE TITLE
Spleef in game countdown; Again;

### ISSUE THREAD

**Issue by aaomidi** [Kaos1337/SimpleSpleef-Evolution#4]
I tested with the new build and the problem is still not solved and I found the cause of it, well if someone joins spleef and then quits the server before /spl ready It cant start the game anymore.AND BAM there goes spleef :P

**Comment by Kaos1337** [comment]
The problem is different, in the ticket #1 the second countdown didn't start for an exception and without that a player logged out.
Only with this issue we noticed that there is this problem too.

Edit:
Now the exception happen only with the logout of a noReady player: http://pastebin.com/6eW5M2c1
Wait...

Edit2:
Happen with all players logged too, really strange bug.

**Comment by aaomidi** [comment]
Yeah I couldn't track out what was happening :?

**Comment by Kaos1337** [comment]
Can you try this dev version? http://www.mediafire.com/?h5xrrx1l91x3al5

**Comment by aaomidi** [comment]
RIP Issue.
